using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using PCG.Library.Collections;
using System.Linq;
using PCG.Library.Story;
using System.Collections.Generic;
using CommonExtensions.NumericExtensions;

namespace PCG.Tests
{
    [TestClass]
    public class MarkovChainTests
    {        
        [TestMethod]
        public void ChainTest()
        {
            var chain = new MarkovChain<string>(2);
            var text = CORPUS.Split(' ');
            chain.Add(text);
            var genText = string.Join(" ", chain.Chain().Take(1000));
            Assert.AreNotEqual(string.Empty, genText);            
        }

        [TestMethod]
        public void NameGeneratorTest()
        {
            var gen = new NameGenerator();
            var names = new List<string>();
            for (int i = 0; i < 100; i++)
            {
                var length = (i % 10).GreaterOf(4);
                var name = gen.MakeName(length);
                names.Add(name);
            }            
        }

        #region Corpus
        private const string CORPUS = 
@"A character mask (German: Charaktermaske) in the Marxian sense is a character disguised with a different character. The term was used by Karl Marx in various published writings from the 1840s to the 1860s, and also by Friedrich Engels. It is related to the classical Greek concepts of mimesis (imitative representation using analogies) and prosopopoeia (impersonation or personification) as well as the Roman concept of persona,[1] but also differs from them (see below).[2] The notion of character masks has been used by neo-Marxist and non-Marxist sociologists,[3] philosophers[4] and anthropologists[5] to interpret how people relate in societies with a complex division of labour, where people depend on trade to meet many of their needs.
As a critical concept, bearing character masks contrasts with the concept of ""role-taking"" developed by social theorists such as George Herbert Mead, Ralph Linton, Talcott Parsons, Theodore R. Sarbin and Ralf Dahrendorf, as well as Robert K. Merton's idea of a role set, in the first instance because ""social roles"" do not necessarily assume the masking of behaviour, and Marx's character masks do not necessarily assume agreement with roles, or that the roles are fixed (see role theory).[6]
The concept of a character mask, and more generally the concept of masks, can be regarded as one of the simplest and oldest in human social theory.[7] Yet it is also connected to the most difficult issues about the interaction between the self and the social world.[8] Indian experts say that ""Masks are one of the earliest creations of humans to establish a relationship between the outer world and the inner person"".[9] The Jungian psychologist Jolande Jacobi commented that ""With the advance of civilization, the mask, originally connected with the gods and animated by them, has become through constant use an everyday necessity.""[10] The Nepalese scholar Shanker Thapa claims that the concept of masks is ""not much highlighted in the scholarly world"" and that ""its relation to human creativity and nature are ignored"" – a ""precise scientific and cultural analysis and elaboration is still lacking.""[11]
Marx's own idea of character masks was not a cut-and-dried academic concept with a fixed definition. Instead, it was a living idea which evolved across half a century. Different Marxist thinkers subsequently developed the idea further in various new contexts.
The concept of character masks refers to the assumption of functions in which people ""act out"" roles, whether voluntarily, by necessity, or by force. In those roles, some or all of their true characteristics and intentions may be partly or wholly masked. Their activity may have broader social effects that they would rather not know about, which they wish to be unknown or presented in a certain light, or which they are unaware of, and therefore the effects are mentally disconnected from their real causes. Accordingly persons and their relationships may no longer be quite what they seem to be, and there is a difference between their personal and their functional (or formal) relationships. Even if the ""masking"" is readily observable and known, what the true character is, may remain unknown. The ultimate in acting is achieved when the actors and actresses are able to impersonate characters so well and so completely, that their audience cannot distinguish the act from the real thing (and the actors and actresses themselves start to believe they really are someone else).
As a psychological term, ""character"" is traditionally used more in continental Europe, while in Britain and North America the term ""personality"" is used in approximately the same contexts.[12] Marx however uses the term ""character mask"" analogously to a theatrical role, where the actor (or the characteristics of a prop) represents a certain interest or function, and intends by character both ""the characteristics of somebody"" and ""the characteristics of something"". He was writing a century before role theory became an academically recognized subject in sociology.[13] Marx's metaphorical use of the term ""character masks"" refers to carnival masks and the masks used in classical Greek theatre. At issue is the social form in which a practice is acted out.
A sophisticated academic language for talking about the sociology of roles did not exist in the mid-19th century. Marx therefore borrowed from theatre and literature to express his idea.[14] Although György Lukács pioneered a sociology of drama in 1909,[15] a sociology of roles began only in the 1930s, and a specific sociology of theatre (e.g. by Jean Duvignaud) first emerged in the 1960s.[16] Marx's concept is both that an identity appears differently from its true identity (it is masked or disguised), and that this difference has very real practical consequences (the mask is not simply a decoration, but performs a real function and has real effects, even independently of the mask bearer).
The nearest equivalent term in modern English for Marx's ""character masks"" is social masks. However, such a translation is not entirely satisfactory, for several reasons:
A ""social mask"" is normally understood only as the mask of an individual, while Marx's concept of character masks has been applied by Marxists and non-Marxists to persons and politicians,[17] groups and social classes, mass media, social movements and political parties, social institutions, organizations and functions, governments, symbolic expressions, historical eras, and dramatic, literary or theatrical contexts. In each case, the suggestion is that matters present themselves other than they really are.[18]
Marx's character masks are a specific kind of social masks, i.e. masks of people and things which represent a social, political, intellectual or economic function, within the given social relationships among groups of people. The category of ""social masks"" is much more general and inclusive.
With Marx's character masks, it is understood that they are bound up with a specific type of society at a specific historical time, and with a specific theory of how the social relations in that society function. By contrast, the general concept of ""social masks"" assumes no specific theory, specific society or specific historical time; social masks of whatever form can be assumed to have existed forever and a day, and thus are treated as a more or less permanent part of the human condition.
Nevertheless, the Argentinian/Spanish sociologist Pablo Nacach has used the concept of ""social masks"" in a wider, critical sense.[19]
There is a link between character masks and the concept of deliberate misrepresentation and hypocrisy.[20] Yet character masks need not be hypocritical, insofar as the motive for their use is genuine, sincere, principled or naive – or a product of (self-)delusion. People can also mask their behaviour, or mask a situation, without being aware that they are doing so.[21] Paul Ricœur explains:
What distinguishes false-consciousness from error or falsehood, and what motivates a particular kind of critique, of denunciation, is the possibility of signifying another thing than one believes was signified, that is, the possibility of the masked consciousness. These two words, ""false consciousness,"" pertain usually to Marx... Consciousness, far from being transparent in itself, is at the same time what reveals and what conceals; it is this relation of conceal/reveal which calls for a specific reading, a hermeneutics. The task of hermeneutics... has always been to read a text and to distinguish the true sense from the apparent sense, to search for the sense under the sense.[22]
The ""false awareness"" (falsches Bewusstsein) in the classical sense used by Friedrich Engels does not necessarily refer to ""errors"" in the content of awareness. It refers rather to an absence of awareness of what is really behind the ideas being worked with, how they have originated, or what the real role or effect of the ideas is. The first result of that is, that the ideologists believe themselves to be performing certain intellectual operations with regard to an issue, which, in reality, have quite a different significance than what they imagine. The second result is that their intellectual creations can then function as a mask for what is really at stake, precisely because the issue is portrayed in a one-sided or distorted way – without the ideologists being aware of how that works. The ideologists are aware and unaware at the same time. The problem, says Engels, is that they exaggerate the power of ideas, even to the point where ideas seem to be the cause of all that happens. This occurs especially if the intellectual productions occur at quite some distance from the practical context to which they properly refer, or if they concern specialized, highly abstract ideas which cannot easily be verified[23] (this concept differs from the Marxism–Leninism ideology, where ""false consciousness"" is thinking which deviates from the political line of the Communist Party).
Masking need not involve deliberate lying or fraud. It may merely involve the projection of an image, shape or sound which the observer chooses to, or is likely to, interpret in a particular way (it could also be interpreted in many other, quite different ways). In fact, Marx suggests that insofar as people work in various roles and functions, a character mask can be a ""normal"" part of the role. In his 1891 essay The Critic as Artist, Oscar Wilde remarks that paradoxically ""Man is least himself when he talks in his own person. Give him a mask, and he will tell you the truth."" [24]
There are numerous novels,[25] thrillers, horror stories[26] and biographies which explore the human character that exists ""behind the mask"" from various points of view. There are also numerous books by religious authors[27] and psychologists[28] dealing with the way in which people seek to ""cover up"" the impact of a mistake, a sin, an injury or a trauma by carrying on a pretense which involves the masking of behaviour.
However, while this kind of literature does illustrate that character masks of all kinds are a durable feature of the human condition – arising out of the great behavioural flexibility of the human species, acquired through a lengthy process of evolution – they do not necessarily have anything to do with Marx's critique of bourgeois society as a whole, and the character masks which Marx thought were specific to (or ""characteristic"" of) that society. The human practice of masking, whether for ritualistic, cultural or practical reasons, predates the origin of class societies by thousands of years.[29]
The ""character masks of an era"" refer, according to Marx and Engels, to its main symbolic expressions of self-justification or apologism, the function of which is to disguise, embellish or mystify social contradictions (""the bits that do not fit""). A purported ""mystical truth"" in this context is a meaning which cannot be definitely proved, because it results from an abstractive procedure or cognition which is not logical, and cannot be tested scientifically, only subjectively experienced.
Terry Eagleton explains:
A dominant power may legitimate itself by promoting beliefs and values congenial to it; naturalizing and universalizing such beliefs so as to render them self-evident and apparently inevitable; denigrating ideas which might challenge it; excluding rival forms of thought, perhaps by some unspoken but systematic logic; and obscuring social reality in ways convenient to itself. Such `mystification', as it is commonly known, frequently takes the form of masking[30]
For example, a concept such as ""globalization"" has no fixed meaning (it is a buzzword or fuzzy concept). This makes it a very convenient expression to justify any kind of international orientation or policy, or present the worldwide expansion of capitalism as inevitable. This approach creates the impression that ""globalization"" has a definite technical meaning and a reality, which professional experts can specify, but, in fact, even the experts cannot agree about its meaning.[31]
Marx also argues that, insofar as capitalist class society is intrinsically a very contradictory system – it contains many conflicting and competing forces – the masking of its true characteristics becomes an integral feature of how it actually operates. Buyers and sellers compete with other buyers and sellers. Businesses cannot practically do so without confidentiality and secrecy. Workers compete for job opportunities and access to resources. Capitalists and workers compete for their share of the new wealth that is produced, and nations compete with other nations. The masks are therefore not optional, but necessary, and the more one is able to know about others, the more subtle, ingenious and sophisticated the masks become.
One of the centrepieces of Marx's critique of political economy is that the juridical labour contract between the worker and his capitalist employer obscures the true economic relationship, which is (according to Marx) that the workers do not sell their labour, but their labour power, making possible a profitable difference between what they are paid and the new value they create for the owners of capital (a form of economic exploitation). Thus, the very foundation of capitalist wealth creation involves – as Marx says explicitly – a ""mask"".[32] More generally, Marx argues that transactions in the capitalist economy are often far from transparent – they appear different from what they really are. This is discovered, only when one probes the total context in which they occur. Hence Marx writes:
Vulgar economics actually does nothing more than to interpret, to systematize and turn into apologetics – in a doctrinaire way – the ideas of the agents who are trapped within bourgeois relations of production. So it should not surprise us that, precisely within the estranged form of appearance of economic relations in which these prima facie absurd and complete contradictions occur – and all science would be superfluous if the form of appearance of things directly coincided with their essence – that precisely here vulgar economics feels completely at home, and that these relationships appear all the more self-evident to it, the more their inner interconnection remains hidden to it, even though these relationships are comprehensible to the popular mind[33]
This implies another level of masking, because the economic character masks are then straightforwardly (""vulgarly"") equated with authentic behaviour. The effect in this case is, that the theory of ""how the economy works"" masks how it actually works, by conflating its surface appearance with its real nature. Its generalities seem to explain it, but in reality they do not. The theory is therefore (ultimately) arbitrary. Either things are studied in isolation from the total context in which they occur, or generalizations are formed which leave essential bits out. Such distortion can certainly be ideologically useful to justify an economic system, position or policy as a good thing, but it can become a hindrance to understanding.[34]";
        #endregion
    }
}
